### Final Project | Music & Mental Health (1)

In [1]:
# Import Libraries:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

https://www.kaggle.com/datasets/catherinerasgaitis/mxmh-survey-results/data

In [2]:
# Read Dataset

data_mmh = pd.read_csv('../../data/raw/mxmh_survey_results.csv')
data_mmh

Timestamp   Age Primary streaming service  Hours per day  \
0     8/27/2022 19:29:02  18.0                   Spotify            3.0   
1     8/27/2022 19:57:31  63.0                   Pandora            1.5   
2     8/27/2022 21:28:18  18.0                   Spotify            4.0   
3     8/27/2022 21:40:40  61.0             YouTube Music            2.5   
4     8/27/2022 21:54:47  18.0                   Spotify            4.0   
..                   ...   ...                       ...            ...   
731  10/30/2022 14:37:28  17.0                   Spotify            2.0   
732   11/1/2022 22:26:42  18.0                   Spotify            1.0   
733   11/3/2022 23:24:38  19.0   Other streaming service            6.0   
734   11/4/2022 17:31:47  19.0                   Spotify            5.0   
735    11/9/2022 1:55:20  29.0             YouTube Music            2.0   

    While working Instrumentalist Composer         Fav genre Exploratory  \
0             Yes             Yes      Yes             Latin         Yes   
1             Yes              No       No              Rock         Yes   
2              No              No       No  Video game music          No   
3             Yes              No      Yes              Jazz         Yes   
4             Yes              No       No               R&B         Yes   
..            ...             ...      ...               ...         ...   
731           Yes             Yes       No              Rock         Yes   
732           Yes             Yes       No               Pop         Yes   
733           Yes              No      Yes               Rap         Yes   
734           Yes             Yes       No         Classical          No   
735           Yes              No       No           Hip hop         Yes   

    Foreign languages  ...  Frequency [R&B]  Frequency [Rap] Frequency [Rock]  \
0                 Yes  ...        Sometimes  Very frequently            Never   
1                  No  ...        Sometimes           Rarely  Very frequently   
2                 Yes  ...            Never           Rarely           Rarely   
3                 Yes  ...        Sometimes            Never            Never   
4                  No  ...  Very frequently  Very frequently            Never   
..                ...  ...              ...              ...              ...   
731               Yes  ...            Never           Rarely  Very frequently   
732               Yes  ...            Never            Never        Sometimes   
733                No  ...        Sometimes        Sometimes           Rarely   
734                No  ...            Never            Never            Never   
735               Yes  ...  Very frequently  Very frequently  Very frequently   

    Frequency [Video game music] Anxiety Depression Insomnia  OCD  \
0                      Sometimes     3.0        0.0      1.0  0.0   
1                         Rarely     7.0        2.0      2.0  1.0   
2                Very frequently     7.0        7.0     10.0  2.0   
3                          Never     9.0        7.0      3.0  3.0   
4                         Rarely     7.0        2.0      5.0  9.0   
..                           ...     ...        ...      ...  ...   
731                        Never     7.0        6.0      0.0  9.0   
732                    Sometimes     3.0        2.0      2.0  5.0   
733                       Rarely     2.0        2.0      2.0  2.0   
734                    Sometimes     2.0        3.0      2.0  1.0   
735                       Rarely     2.0        2.0      2.0  5.0   

    Music effects    Permissions  
0             NaN  I understand.  
1             NaN  I understand.  
2       No effect  I understand.  
3         Improve  I understand.  
4         Improve  I understand.  
..            ...            ...  
731       Improve  I understand.  
732       Improve  I understand.  
733       Improve  I understand.  
734       Improve  I understand.  
735       Impr

In [3]:
data_mmh.shape

(736, 33)

In [4]:
data_mmh['Music effects'].value_counts()

Music effects
Improve      542
No effect    169
Worsen        17
Name: count, dtype: int64

In [5]:
data_mmh.head()

Timestamp   Age Primary streaming service  Hours per day  \
0  8/27/2022 19:29:02  18.0                   Spotify            3.0   
1  8/27/2022 19:57:31  63.0                   Pandora            1.5   
2  8/27/2022 21:28:18  18.0                   Spotify            4.0   
3  8/27/2022 21:40:40  61.0             YouTube Music            2.5   
4  8/27/2022 21:54:47  18.0                   Spotify            4.0   

  While working Instrumentalist Composer         Fav genre Exploratory  \
0           Yes             Yes      Yes             Latin         Yes   
1           Yes              No       No              Rock         Yes   
2            No              No       No  Video game music          No   
3           Yes              No      Yes              Jazz         Yes   
4           Yes              No       No               R&B         Yes   

  Foreign languages  ...  Frequency [R&B]  Frequency [Rap] Frequency [Rock]  \
0               Yes  ...        Sometimes  Very frequently            Never   
1                No  ...        Sometimes           Rarely  Very frequently   
2               Yes  ...            Never           Rarely           Rarely   
3               Yes  ...        Sometimes            Never            Never   
4                No  ...  Very frequently  Very frequently            Never   

  Frequency [Video game music] Anxiety Depression Insomnia  OCD Music effects  \
0                    Sometimes     3.0        0.0      1.0  0.0           NaN   
1                       Rarely     7.0        2.0      2.0  1.0           NaN   
2              Very frequently     7.0        7.0     10.0  2.0     No effect   
3                        Never     9.0        7.0      3.0  3.0       Improve   
4                       Rarely     7.0        2.0      5.0  9.0       Improve   

     Permissions  
0  I understand.  
1  I understand.  
2  I understand.  
3  I understand.  
4  I understand.  

[5 rows x 33 columns]

In [6]:
# Display columns:

#display(data_mmh.columns)
data_mmh.columns

Index(['Timestamp', 'Age', 'Primary streaming service', 'Hours per day',
       'While working', 'Instrumentalist', 'Composer', 'Fav genre',
       'Exploratory', 'Foreign languages', 'BPM', 'Frequency [Classical]',
       'Frequency [Country]', 'Frequency [EDM]', 'Frequency [Folk]',
       'Frequency [Gospel]', 'Frequency [Hip hop]', 'Frequency [Jazz]',
       'Frequency [K pop]', 'Frequency [Latin]', 'Frequency [Lofi]',
       'Frequency [Metal]', 'Frequency [Pop]', 'Frequency [R&B]',
       'Frequency [Rap]', 'Frequency [Rock]', 'Frequency [Video game music]',
       'Anxiety', 'Depression', 'Insomnia', 'OCD', 'Music effects',
       'Permissions'],
      dtype='object')

In [7]:
# Rename column 'Fav Genre'
data_mmh = data_mmh.rename(columns={"Fav genre":"Favorite genre"})
data_mmh.head()

Timestamp   Age Primary streaming service  Hours per day  \
0  8/27/2022 19:29:02  18.0                   Spotify            3.0   
1  8/27/2022 19:57:31  63.0                   Pandora            1.5   
2  8/27/2022 21:28:18  18.0                   Spotify            4.0   
3  8/27/2022 21:40:40  61.0             YouTube Music            2.5   
4  8/27/2022 21:54:47  18.0                   Spotify            4.0   

  While working Instrumentalist Composer    Favorite genre Exploratory  \
0           Yes             Yes      Yes             Latin         Yes   
1           Yes              No       No              Rock         Yes   
2            No              No       No  Video game music          No   
3           Yes              No      Yes              Jazz         Yes   
4           Yes              No       No               R&B         Yes   

  Foreign languages  ...  Frequency [R&B]  Frequency [Rap] Frequency [Rock]  \
0               Yes  ...        Sometimes  Very frequently            Never   
1                No  ...        Sometimes           Rarely  Very frequently   
2               Yes  ...            Never           Rarely           Rarely   
3               Yes  ...        Sometimes            Never            Never   
4                No  ...  Very frequently  Very frequently            Never   

  Frequency [Video game music] Anxiety Depression Insomnia  OCD Music effects  \
0                    Sometimes     3.0        0.0      1.0  0.0           NaN   
1                       Rarely     7.0        2.0      2.0  1.0           NaN   
2              Very frequently     7.0        7.0     10.0  2.0     No effect   
3                        Never     9.0        7.0      3.0  3.0       Improve   
4                       Rarely     7.0        2.0      5.0  9.0       Improve   

     Permissions  
0  I understand.  
1  I understand.  
2  I understand.  
3  I understand.  
4  I understand.  

[5 rows x 33 columns]

In [8]:
data_mmh.shape[0]

736

In [9]:
len(data_mmh)

736

### Drop columns
Because in this context of the research these columns are not necessary.
"Primary streaming service" may be related to song recommendations could be interesting in future research.

In [10]:
# Drop columns "Timestamp" and "Primary streaming service":

In [11]:
# Check columns
data_mmh['Timestamp'].value_counts()

Timestamp
8/28/2022 16:15:08    2
8/27/2022 19:29:02    1
9/1/2022 21:07:33     1
9/1/2022 19:09:32     1
9/1/2022 19:36:54     1
                     ..
8/28/2022 23:34:19    1
8/28/2022 23:34:37    1
8/28/2022 23:40:54    1
8/28/2022 23:42:24    1
11/9/2022 1:55:20     1
Name: count, Length: 735, dtype: int64

In [12]:
# Check for missing values in 'Timestamp'
data_mmh['Timestamp'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...  
731    False
732    False
733    False
734    False
735    False
Name: Timestamp, Length: 736, dtype: bool

In [13]:
# Create a new empty list called drop_list
drop_list = []

# Add the following columns to this: "Timestamp" , "Primary streaming service"
#drop_list.append("Timestamp" , "Primary streaming service")
drop_list.append("Timestamp")
drop_list

['Timestamp']

In [14]:
drop_list.append("Primary streaming service")
drop_list

['Timestamp', 'Primary streaming service']

In [15]:
# Drop columns "Timestamp" and "Primary streaming service":
data_mmh.drop(columns=drop_list, inplace=True)
#data_mmh.head()

### Identify missing values

In [16]:
nulls_df = pd.DataFrame(data_mmh.isna().sum()).reset_index()
nulls_df.columns = ["column","nas"]
nulls_df[nulls_df['nas'] > 0]

column  nas
0                 Age    1
2       While working    3
3     Instrumentalist    4
4            Composer    1
7   Foreign languages    4
8                 BPM  107
29      Music effects    8

In [17]:
data_mmh ['Age'].unique()

array([18., 63., 61., 21., 19., nan, 17., 16., 15., 14., 20., 26., 23.,
       37., 36., 24., 22., 42., 25., 32., 29., 41., 31., 33., 30., 43.,
       28., 34., 13., 35., 27., 53., 49., 60., 38., 44., 40., 64., 56.,
       59., 10., 12., 54., 57., 69., 72., 73., 39., 58., 67., 70., 55.,
       48., 71., 74., 51., 65., 80., 50., 68., 46., 89.])

In [18]:
data_mmh ['Hours per day'].unique()

array([ 3.  ,  1.5 ,  4.  ,  2.5 ,  5.  ,  1.  ,  6.  ,  8.  ,  2.  ,
       12.  , 24.  ,  0.5 ,  0.25,  0.  ,  7.  , 10.  ,  9.  ,  0.7 ,
        4.5 , 20.  , 16.  , 15.  , 14.  , 13.  ,  0.1 , 11.  , 18.  ])

In [19]:
data_mmh ['While working'].unique()

array(['Yes', 'No', nan], dtype=object)

In [20]:
data_mmh ['Instrumentalist'].unique()

array(['Yes', 'No', nan], dtype=object)

In [21]:
data_mmh ['Composer'].unique()

array(['Yes', 'No', nan], dtype=object)

In [22]:
data_mmh ['Favorite genre'].unique()

array(['Latin', 'Rock', 'Video game music', 'Jazz', 'R&B', 'K pop',
       'Country', 'EDM', 'Hip hop', 'Pop', 'Rap', 'Classical', 'Metal',
       'Folk', 'Lofi', 'Gospel'], dtype=object)

In [23]:
data_mmh ['Exploratory'].unique()

array(['Yes', 'No'], dtype=object)

In [24]:
data_mmh ['Foreign languages'].unique()

array(['Yes', 'No', nan], dtype=object)

In [25]:
data_mmh ['BPM'].unique()

array([1.56000000e+02, 1.19000000e+02, 1.32000000e+02, 8.40000000e+01,
       1.07000000e+02, 8.60000000e+01, 6.60000000e+01, 9.50000000e+01,
       9.40000000e+01, 1.55000000e+02,            nan, 1.25000000e+02,
       8.80000000e+01, 1.48000000e+02, 1.03000000e+02, 1.20000000e+02,
       9.90000000e+01, 1.18000000e+02, 7.90000000e+01, 1.69000000e+02,
       1.36000000e+02, 1.01000000e+02, 1.26000000e+02, 1.83000000e+02,
       1.42000000e+02, 7.50000000e+01, 8.90000000e+01, 1.40000000e+02,
       1.61000000e+02, 8.00000000e+01, 1.30000000e+02, 1.47000000e+02,
       7.70000000e+01, 1.15000000e+02, 1.57000000e+02, 9.00000000e+01,
       1.28000000e+02, 9.60000000e+01, 9.10000000e+01, 5.50000000e+01,
       8.50000000e+01, 1.60000000e+02, 1.08000000e+02, 1.70000000e+02,
       1.74000000e+02, 1.27000000e+02, 1.65000000e+02, 1.13000000e+02,
       1.67000000e+02, 1.10000000e+02, 1.50000000e+02, 9.30000000e+01,
       1.09000000e+02, 1.75000000e+02, 1.62000000e+02, 1.89000000e+02,
      

In [26]:
data_mmh ["Frequency [Classical]"].unique()

array(['Rarely', 'Sometimes', 'Never', 'Very frequently'], dtype=object)

In [27]:
data_mmh ["Frequency [Country]"].unique()

array(['Never', 'Sometimes', 'Very frequently', 'Rarely'], dtype=object)

In [28]:
data_mmh ["Frequency [EDM]"].unique()

array(['Rarely', 'Never', 'Very frequently', 'Sometimes'], dtype=object)

In [29]:
data_mmh ["Frequency [Folk]"].unique()

array(['Never', 'Rarely', 'Sometimes', 'Very frequently'], dtype=object)

In [30]:
data_mmh ["Frequency [Gospel]"].unique()

array(['Never', 'Sometimes', 'Rarely', 'Very frequently'], dtype=object)

In [31]:
data_mmh ["Frequency [Hip hop]"].unique()

array(['Sometimes', 'Rarely', 'Never', 'Very frequently'], dtype=object)

In [32]:
data_mmh ["Frequency [Jazz]"].unique()

array(['Never', 'Very frequently', 'Rarely', 'Sometimes'], dtype=object)

In [33]:
data_mmh ["Frequency [K pop]"].unique()

array(['Very frequently', 'Rarely', 'Sometimes', 'Never'], dtype=object)

In [34]:
data_mmh ["Frequency [Latin]"].unique()

array(['Very frequently', 'Sometimes', 'Never', 'Rarely'], dtype=object)

In [35]:
data_mmh ["Frequency [Lofi]"].unique()

array(['Rarely', 'Sometimes', 'Very frequently', 'Never'], dtype=object)

In [36]:
data_mmh ["Frequency [Metal]"].unique()

array(['Never', 'Sometimes', 'Rarely', 'Very frequently'], dtype=object)

In [37]:
data_mmh ["Frequency [Pop]"].unique()

array(['Very frequently', 'Sometimes', 'Rarely', 'Never'], dtype=object)

In [38]:
data_mmh ["Frequency [R&B]"].unique()

array(['Sometimes', 'Never', 'Very frequently', 'Rarely'], dtype=object)

In [39]:
data_mmh ["Frequency [Rap]"].unique()

array(['Very frequently', 'Rarely', 'Never', 'Sometimes'], dtype=object)

In [40]:
data_mmh ["Frequency [Rock]"].unique()

array(['Never', 'Very frequently', 'Rarely', 'Sometimes'], dtype=object)

In [41]:
data_mmh ["Frequency [Video game music]"].unique()

array(['Sometimes', 'Rarely', 'Very frequently', 'Never'], dtype=object)

In [42]:
data_mmh ["Anxiety"].unique()

array([ 3. ,  7. ,  9. ,  8. ,  4. ,  5. ,  2. ,  1. ,  6. , 10. ,  0. ,
        7.5])

In [43]:
data_mmh ["Depression"].unique()

array([ 0. ,  2. ,  7. ,  8. ,  3. ,  1. ,  4. ,  5. ,  9. , 10. ,  6. ,
        3.5])

In [44]:
data_mmh ["OCD"].unique()

array([ 0. ,  1. ,  2. ,  3. ,  9. ,  7. ,  4. ,  6. , 10. ,  5. ,  8. ,
        8.5,  5.5])

In [45]:
data_mmh ["Music effects"].unique()

array([nan, 'No effect', 'Improve', 'Worsen'], dtype=object)

In [46]:
data_mmh ["Permissions"].unique()

array(['I understand.'], dtype=object)

### Columns with missing values

In [47]:
# Columns with missing values:
data_mmh ['Age'].unique()
data_mmh ['While working'].unique()
data_mmh ['Instrumentalist'].unique()
data_mmh ['Composer'].unique()
data_mmh ['Foreign languages'].unique()
data_mmh ['BPM'].unique()
data_mmh ["Music effects"].unique()

array([nan, 'No effect', 'Improve', 'Worsen'], dtype=object)

In [48]:
data_mmh ['Age'].isna().sum() # 1/736= 0,001

1

In [49]:
data_mmh ['While working'].isna().sum() # 3/736= 0,004

3

In [50]:
data_mmh ['Instrumentalist'].isna().sum() #4/736=0,005

4

In [51]:
data_mmh ['Composer'].isna().sum() # 1/736= 0,001

1

In [52]:
data_mmh ['Foreign languages'].isna().sum() #4/736=0,005

4

In [53]:
data_mmh ['BPM'].isna().sum() # 107/736 = 0,145

107

In [54]:
data_mmh ['Music effects'].isna().sum() # 8/736= 0,01 

8

In [55]:
len(data_mmh)

736

In [56]:
# Identify columns that have over 5% missing values 
data_mmh.columns[(data_mmh.isna().sum()/len(data_mmh)) > 0.05]

Index(['BPM'], dtype='object')

In [57]:
# Identify columns that have over 10% missing values 
data_mmh.columns[(data_mmh.isna().sum()/len(data_mmh)) > 0.10]

Index(['BPM'], dtype='object')

In [58]:
# Identify columns that have over 14% missing values 
data_mmh.columns[(data_mmh.isna().sum()/len(data_mmh)) > 0.14]

Index(['BPM'], dtype='object')

In [59]:
# Identify columns that have over 15% missing values 
data_mmh.columns[(data_mmh.isna().sum()/len(data_mmh)) > 0.15]

Index([], dtype='object')

In [60]:
"""
['Age' 1, mean/median KNN imputer based  on value of aal column , drop because its one
 'While working', 3 mode drop
 'Instrumentalist', 4 mode drop
 'Composer',1 mode drop 
 'Foreign languages',4 mode drop rows or columns
 'BPM', 107 mean/median replace KNN imputer, if you nknow preference median BPM according to most freq music genre
 replace BPM with median of favorite music genre
 'Music effects'8 mode drop
 """

"\n['Age' 1, mean/median KNN imputer based  on value of aal column , drop because its one\n 'While working', 3 mode drop\n 'Instrumentalist', 4 mode drop\n 'Composer',1 mode drop \n 'Foreign languages',4 mode drop rows or columns\n 'BPM', 107 mean/median replace KNN imputer, if you nknow preference median BPM according to most freq music genre\n replace BPM with median of favorite music genre\n 'Music effects'8 mode drop\n "

### Drop rows with missing values (except 'BPM')

In [61]:
drop_list_rows = []

#for col in data.columns[(data.isna().sum()/len(data)) < 0.05]:
    #drop_list.append(col)


for col in data_mmh.columns[(data_mmh.isna().sum()/len(data_mmh)) > 0.0]:
    drop_list_rows.append(col)

drop_list_rows

['Age',
 'While working',
 'Instrumentalist',
 'Composer',
 'Foreign languages',
 'BPM',
 'Music effects']

In [62]:
data_mmh[drop_list_rows].loc[data_mmh['BPM'].isna(),:]

Age While working Instrumentalist Composer Foreign languages  BPM  \
10   18.0           Yes             Yes       No                No  NaN   
12    NaN           Yes              No       No               Yes  NaN   
15   17.0            No              No       No               Yes  NaN   
30   20.0           Yes             Yes       No               Yes  NaN   
32   19.0           Yes             Yes       No               Yes  NaN   
..    ...           ...             ...      ...               ...  ...   
688  18.0           Yes              No       No                No  NaN   
700  20.0           Yes              No       No               Yes  NaN   
706  23.0           Yes             Yes       No               Yes  NaN   
712  23.0           Yes              No       No                No  NaN   
717  23.0            No              No       No               Yes  NaN   

    Music effects  
10      No effect  
12        Improve  
15         Worsen  
30        Improve  
32        Improve  
..            ...  
688     No effect  
700        Worsen  
706       Improve  
712       Improve  
717     No effect  

[107 rows x 7 columns]

In [63]:
drop_list_rows = [col for col in drop_list_rows if col != "BPM"]
drop_list_rows

['Age',
 'While working',
 'Instrumentalist',
 'Composer',
 'Foreign languages',
 'Music effects']

In [64]:
# Drop rows with missing values in specific columns without 'BPM'
#data = data.dropna(subset=['column1', 'column2'])
data_mmh = data_mmh.dropna(subset=drop_list_rows)

In [65]:
data_mmh.isna().sum()

Age                               0
Hours per day                     0
While working                     0
Instrumentalist                   0
Composer                          0
Favorite genre                    0
Exploratory                       0
Foreign languages                 0
BPM                             102
Frequency [Classical]             0
Frequency [Country]               0
Frequency [EDM]                   0
Frequency [Folk]                  0
Frequency [Gospel]                0
Frequency [Hip hop]               0
Frequency [Jazz]                  0
Frequency [K pop]                 0
Frequency [Latin]                 0
Frequency [Lofi]                  0
Frequency [Metal]                 0
Frequency [Pop]                   0
Frequency [R&B]                   0
Frequency [Rap]                   0
Frequency [Rock]                  0
Frequency [Video game music]      0
Anxiety                           0
Depression                        0
Insomnia                    

### Identify missing values
### How to handle these missing values

In [66]:
data_mmh.isna().sum()

Age                               0
Hours per day                     0
While working                     0
Instrumentalist                   0
Composer                          0
Favorite genre                    0
Exploratory                       0
Foreign languages                 0
BPM                             102
Frequency [Classical]             0
Frequency [Country]               0
Frequency [EDM]                   0
Frequency [Folk]                  0
Frequency [Gospel]                0
Frequency [Hip hop]               0
Frequency [Jazz]                  0
Frequency [K pop]                 0
Frequency [Latin]                 0
Frequency [Lofi]                  0
Frequency [Metal]                 0
Frequency [Pop]                   0
Frequency [R&B]                   0
Frequency [Rap]                   0
Frequency [Rock]                  0
Frequency [Video game music]      0
Anxiety                           0
Depression                        0
Insomnia                    

### KNNImputer for replacing missing values

In [67]:
from sklearn.impute import KNNImputer

# Pick the dataframe without NA'set in 'BPM'
# From the previous dataframe select all the columns except 'BPM'
# set a value for k_neighbours 
# Create an instance of KNNIMputer(k_neigbours) and get the predicted values.
# Compare the predicted values against the real values.

# Extract the specific column with missing values
#column_name = 'your_column_name'  # Replace with the name of the column
#column_with_missing = data[[column_name]]

df_no_nas_in_bpm = data_mmh[data_mmh.isna()==False].select_dtypes(np.number)

medians = [] # [(median, k_negino), ()]
for k_neighbors in range(2,11):
    knn_imputer = KNNImputer(n_neighbors=k_neighbors)
    imputed_np = knn_imputer.fit_transform(df_no_nas_in_bpm)
    imputed_df = pd.DataFrame(imputed_np, columns=df_no_nas_in_bpm.columns, index=df_no_nas_in_bpm.index)
    df_no_nas_in_bpm['BPM_imputed'] = imputed_df['BPM'].values
    df_no_nas_in_bpm['diff'] = df_no_nas_in_bpm['BPM'] - df_no_nas_in_bpm['BPM_imputed']
    medians.append((df_no_nas_in_bpm['diff'].median(), k_neighbors))

#medians = sorted(medians)
medians


#column_name = 'BPM'  # Replace with the name of the column
#column_with_missing = data_mmh[[column_name]]

# Create a KNN imputer object with the desired number of neighbors (K)
#k_neighbors = 0  # Replace with your desired number of neighbors
#knn_imputer = KNNImputer(n_neighbors=k_neighbors)

# Perform imputation on the extracted column
#imputed_column = knn_imputer.fit_transform(column_with_missing)

# Replace the missing values in the original column with the imputed values
#data[column_name] = imputed_column
#data_mmh[column_name] = imputed_column[column_name] #Ignacio
#data_mmh[column_name] = imputed_column

# The missing values in 'your_column_name' have been replaced with imputed values

[(0.0, 2),
 (0.0, 3),
 (0.0, 4),
 (0.0, 5),
 (0.0, 6),
 (0.0, 7),
 (0.0, 8),
 (0.0, 9),
 (0.0, 10)]

In [70]:
# We get the row indexes of the rows that have a na on BPM
indexes_with_nas_in_bpm = data_mmh[data_mmh['BPM'].isna()].index

print(len(indexes_with_nas_in_bpm))
# We get the column index of column BPM
bpm_index = list(data_mmh.columns).index('BPM')

print(bpm_index)

# We create a df with the rows that have a na in BPM and all the numerical columns
temp_df = data_mmh.iloc[indexes_with_nas_in_bpm, :].select_dtypes(np.number)

print(len(temp_df))
# We create an imputer
knn_imputer = KNNImputer(n_neighbors=5)

# We get the predictions of the imputer as np.array
imputed_np = knn_imputer.fit_transform(temp_df)

# We cast the numpy array as a Pandas DataFrame
imputed_df = pd.DataFrame(imputed_np, columns=temp_df.columns, index=temp_df.index)

print(len(imputed_df))
bpm_index_imputed = list(imputed_df.columns).index('BPM')
display(data_mmh.iloc[indexes_with_nas_in_bpm,:].head())
display(temp_df.head())
display(imputed_df.head())

# We replace the rows that contained nas with the imputed values of the Imputer
data_mmh.iloc[indexes_with_nas_in_bpm, bpm_index] = imputed_df.iloc[indexes_with_nas_in_bpm, bpm_index_imputed]

#data_mmh.isna().sum()

102
8
102
102


Age  Hours per day While working Instrumentalist Composer  \
13  19.0            2.0           Yes              No       No   
18  17.0           24.0           Yes              No       No   
33  17.0            4.0            No              No       No   
35  18.0            5.0           Yes             Yes       No   
40  23.0            2.0           Yes             Yes      Yes   

      Favorite genre Exploratory Foreign languages    BPM  \
13           Country         Yes                No   88.0   
18               Rap         Yes                No   99.0   
33              Rock         Yes               Yes  142.0   
35               Pop         Yes                No  120.0   
40  Video game music         Yes                No   80.0   

   Frequency [Classical]  ... Frequency [R&B]  Frequency [Rap]  \
13                 Never  ...           Never  Very frequently   
18                Rarely  ...       Sometimes  Very frequently   
33                Rarely  ...          Rarely        Sometimes   
35             Sometimes  ...       Sometimes        Sometimes   
40             Sometimes  ...       Sometimes           Rarely   

   Frequency [Rock] Frequency [Video game music] Anxiety Depression Insomnia  \
13            Never                        Never     2.0        1.0      2.0   
18  Very frequently                        Never     7.0        5.0      0.0   
33  Very frequently                       Rarely     5.0        6.0      6.0   
35           Rarely                        Never     3.0        2.0      1.0   
40        Sometimes              Very frequently     4.0        2.0      3.0   

    OCD Music effects    Permissions  
13  0.0       Improve  I understand.  
18  3.0       Improve  I understand.  
33  1.0       Improve  I understand.  
35  1.0       Improve  I understand.  
40  4.0       Improve  I understand.  

[5 rows x 31 columns]

Age  Hours per day    BPM  Anxiety  Depression  Insomnia  OCD
13  19.0            2.0   88.0      2.0         1.0       2.0  0.0
18  17.0           24.0   99.0      7.0         5.0       0.0  3.0
33  17.0            4.0  142.0      5.0         6.0       6.0  1.0
35  18.0            5.0  120.0      3.0         2.0       1.0  1.0
40  23.0            2.0   80.0      4.0         2.0       3.0  4.0

Age  Hours per day    BPM  Anxiety  Depression  Insomnia  OCD
13  19.0            2.0   88.0      2.0         1.0       2.0  0.0
18  17.0           24.0   99.0      7.0         5.0       0.0  3.0
33  17.0            4.0  142.0      5.0         6.0       6.0  1.0
35  18.0            5.0  120.0      3.0         2.0       1.0  1.0
40  23.0            2.0   80.0      4.0         2.0       3.0  4.0

IndexError: positional indexers are out-of-bounds

### Decision to drop rows BPM 

Because solving the problem with missing rows in BPM with KNNImputer is taking too long, the decision is been made to also drop these rows. It is a trade off: My dataset will now be smaller. But if I would replace the missing values with the current KNNimputation then I might get a biases model because the values aren't correct. After consultation we decided to drop these rows and continue to finish the datacleaning.

In [73]:
data_mmh[data_mmh['BPM']== 1620868.8589951377]

Empty DataFrame
Columns: [Age, Hours per day, While working, Instrumentalist, Composer, Favorite genre, Exploratory, Foreign languages, BPM, Frequency [Classical], Frequency [Country], Frequency [EDM], Frequency [Folk], Frequency [Gospel], Frequency [Hip hop], Frequency [Jazz], Frequency [K pop], Frequency [Latin], Frequency [Lofi], Frequency [Metal], Frequency [Pop], Frequency [R&B], Frequency [Rap], Frequency [Rock], Frequency [Video game music], Anxiety, Depression, Insomnia, OCD, Music effects, Permissions]
Index: []

[0 rows x 31 columns]

In [74]:
# Identify columns that have over 0% missing values 
data_mmh.columns[(data_mmh.isna().sum()/len(data_mmh)) > 0]

Index(['BPM'], dtype='object')

In [75]:
# Checking columns for missing values

data_mmh.isna().sum()

Age                               0
Hours per day                     0
While working                     0
Instrumentalist                   0
Composer                          0
Favorite genre                    0
Exploratory                       0
Foreign languages                 0
BPM                             102
Frequency [Classical]             0
Frequency [Country]               0
Frequency [EDM]                   0
Frequency [Folk]                  0
Frequency [Gospel]                0
Frequency [Hip hop]               0
Frequency [Jazz]                  0
Frequency [K pop]                 0
Frequency [Latin]                 0
Frequency [Lofi]                  0
Frequency [Metal]                 0
Frequency [Pop]                   0
Frequency [R&B]                   0
Frequency [Rap]                   0
Frequency [Rock]                  0
Frequency [Video game music]      0
Anxiety                           0
Depression                        0
Insomnia                    

The missing values are handled. There are now no missing values present in the dataset.

a K-Nearest Neighbors (KNN) imputer is a way to fill in missing values in a dataset by looking at nearby data points. 

In [76]:
# Check replaced value in 'BPM'
#row = df.iloc[2]
row = data_mmh.iloc[12]
row

Age                                        17.0
Hours per day                               2.0
While working                                No
Instrumentalist                              No
Composer                                     No
Favorite genre                              Pop
Exploratory                                 Yes
Foreign languages                           Yes
BPM                                         NaN
Frequency [Classical]                    Rarely
Frequency [Country]                      Rarely
Frequency [EDM]                           Never
Frequency [Folk]                          Never
Frequency [Gospel]                        Never
Frequency [Hip hop]                   Sometimes
Frequency [Jazz]                         Rarely
Frequency [K pop]                        Rarely
Frequency [Latin]                        Rarely
Frequency [Lofi]                         Rarely
Frequency [Metal]                        Rarely
Frequency [Pop]                 Very fre

### Drop duplicates

In [ ]:
# Checking for duplicates in dataset (rows)
data_mmh.duplicated().sum()

# There are no duplicate rows to drop

In [ ]:
# Saving DataFrames into csv files 

data_mmh.to_csv('../../data/cleaned/data_mmh_cleaned1.csv')